title: Photography
email: carl.castello@yahoo.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/photography"
url: "/"
# twitter_username: jekyllrb
github_username:  carlcastello

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: "assets/scss"
  style: compressed
